### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [ulalu/splurty#2]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by ulalu** [comment]
Hi Michael!

Thanks for the feedback- I didn't realize you needed the mobile meta tags for bootstrap to kick in on smaller devices, but noted that little quirk away for future reference. It should be much more suited to a mobile environment now. (also, RJ says hello!)

**Comment by Mikeysax** [comment]
Awesome! You'll need that tag for only mobile devices.

Hah, how do you know RJ?

**Comment by ulalu** [comment]
We went to college together- he's actually the reason I signed up for
firehose. He said you two worked together on the agile team project almost
by yourselves, and had really good things to say about the experience.
Anyway, it's lovely to meet you!

**Comment by Mikeysax** [comment]
Awesome! Yes, we were a super duo, hah.
Glad to have you aboard :+1:
